"""add_contact_email_to_partners

Revision ID: 4f549e53b1e0
Revises: 02f499d9e01a
Create Date: 2025-04-26 22:06:44.773507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f549e53b1e0'
down_revision: Union[str, None] = '02f499d9e01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('contact_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'contact_email')
    # ### end Alembic commands ###
