"""Add contact_info to partners table

Revision ID: aea0e9746b83
Revises: 4f549e53b1e0
Create Date: 2025-04-26 22:09:33.011338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'aea0e9746b83'
down_revision: Union[str, None] = '4f549e53b1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('contact_info', 
                                        postgresql.JSONB(astext_type=sa.Text()), 
                                        nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'contact_info')
    # ### end Alembic commands ###
